version: '3.4'

services:

  sco.gateway.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  sco.basketservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  sco.productservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  sco.web.ui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  sco.configurationservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
   
  sco.paymentservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  sco.shiftservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
